//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageResources.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Folder 的本地化字符串。
        /// </summary>
        public static string AddFolder {
            get {
                return ResourceManager.GetString("AddFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto check for updates when the program starts 的本地化字符串。
        /// </summary>
        public static string AutoCheckUpdate {
            get {
                return ResourceManager.GetString("AutoCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run program automatically when the system starts 的本地化字符串。
        /// </summary>
        public static string AutoRunProgram {
            get {
                return ResourceManager.GetString("AutoRunProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time Interval of Auto Switch (0 disables switching) 的本地化字符串。
        /// </summary>
        public static string AutoSwitchInterval {
            get {
                return ResourceManager.GetString("AutoSwitchInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black 的本地化字符串。
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue 的本地化字符串。
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking... 的本地化字符串。
        /// </summary>
        public static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check for updates 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear logging 的本地化字符串。
        /// </summary>
        public static string ClearLogging {
            get {
                return ResourceManager.GetString("ClearLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click the tray icon to do: 的本地化字符串。
        /// </summary>
        public static string ClickTray {
            get {
                return ResourceManager.GetString("ClickTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Desktop Shortcut 的本地化字符串。
        /// </summary>
        public static string CreateDesktopShortcut {
            get {
                return ResourceManager.GetString("CreateDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cyan 的本地化字符串。
        /// </summary>
        public static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark gray 的本地化字符串。
        /// </summary>
        public static string DarkGray {
            get {
                return ResourceManager.GetString("DarkGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop Background Color (Border color): 的本地化字符串。
        /// </summary>
        public static string DesktopBackgroundColor {
            get {
                return ResourceManager.GetString("DesktopBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable desktop wallpaper JPEG quality reduction (Valid only for Windows 10 and later) 的本地化字符串。
        /// </summary>
        public static string DisableQualityReduction {
            get {
                return ResourceManager.GetString("DisableQualityReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double-click the monitor card to do: 的本地化字符串。
        /// </summary>
        public static string DoubleClickCard {
            get {
                return ResourceManager.GetString("DoubleClickCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double-click the folder item to do: 的本地化字符串。
        /// </summary>
        public static string DoubleClickFolder {
            get {
                return ResourceManager.GetString("DoubleClickFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double-click the tray icon to do: 的本地化字符串。
        /// </summary>
        public static string DoubleClickTray {
            get {
                return ResourceManager.GetString("DoubleClickTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable logging for wallpaper settings 的本地化字符串。
        /// </summary>
        public static string EnableLogging {
            get {
                return ResourceManager.GetString("EnableLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string ExitProgram {
            get {
                return ResourceManager.GetString("ExitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export logging 的本地化字符串。
        /// </summary>
        public static string ExportLogging {
            get {
                return ResourceManager.GetString("ExportLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export logging to text document 的本地化字符串。
        /// </summary>
        public static string ExportLoggingToFile {
            get {
                return ResourceManager.GetString("ExportLoggingToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback 的本地化字符串。
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fill 的本地化字符串。
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fit 的本地化字符串。
        /// </summary>
        public static string Fit {
            get {
                return ResourceManager.GetString("Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder List 的本地化字符串。
        /// </summary>
        public static string FolderList {
            get {
                return ResourceManager.GetString("FolderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to upgrade 的本地化字符串。
        /// </summary>
        public static string GoUpgrade {
            get {
                return ResourceManager.GetString("GoUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green 的本地化字符串。
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor options - set the selected monitor. 的本地化字符串。
        /// </summary>
        public static string GroupBoxHeaderMonitorOptions {
            get {
                return ResourceManager.GetString("GroupBoxHeaderMonitorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview - Choose the monitor to configure. 的本地化字符串。
        /// </summary>
        public static string GroupBoxPreviewHeader {
            get {
                return ResourceManager.GetString("GroupBoxPreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New version:  的本地化字符串。
        /// </summary>
        public static string HadUpdate {
            get {
                return ResourceManager.GetString("HadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex triplet 的本地化字符串。
        /// </summary>
        public static string HEX {
            get {
                return ResourceManager.GetString("HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey 的本地化字符串。
        /// </summary>
        public static string HotKey {
            get {
                return ResourceManager.GetString("HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey settings 的本地化字符串。
        /// </summary>
        public static string HotKeySettings {
            get {
                return ResourceManager.GetString("HotKeySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image 的本地化字符串。
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Already the latest version 的本地化字符串。
        /// </summary>
        public static string IsLatest {
            get {
                return ResourceManager.GetString("IsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light gray 的本地化字符串。
        /// </summary>
        public static string LightGray {
            get {
                return ResourceManager.GetString("LightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging 的本地化字符串。
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging count: 的本地化字符串。
        /// </summary>
        public static string LoggingCount {
            get {
                return ResourceManager.GetString("LoggingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 min 的本地化字符串。
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network error! Please try again 的本地化字符串。
        /// </summary>
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open directory of current image 的本地化字符串。
        /// </summary>
        public static string OpenDirectoryOfCurrentImage {
            get {
                return ResourceManager.GetString("OpenDirectoryOfCurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open directory of last setting image 的本地化字符串。
        /// </summary>
        public static string OpenDirectoryOfLastSettingImage {
            get {
                return ResourceManager.GetString("OpenDirectoryOfLastSettingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open directory of setting image 的本地化字符串。
        /// </summary>
        public static string OpenDirectoryOfSettingImage {
            get {
                return ResourceManager.GetString("OpenDirectoryOfSettingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open this folder 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause auto switch 的本地化字符串。
        /// </summary>
        public static string PauseAutoSwitch {
            get {
                return ResourceManager.GetString("PauseAutoSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language (Need to restart the program): 的本地化字符串。
        /// </summary>
        public static string ProgramLanguage {
            get {
                return ResourceManager.GetString("ProgramLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program options 的本地化字符串。
        /// </summary>
        public static string ProgramOptions {
            get {
                return ResourceManager.GetString("ProgramOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purple 的本地化字符串。
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red 的本地化字符串。
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh all cards 的本地化字符串。
        /// </summary>
        public static string RefreshAllCards {
            get {
                return ResourceManager.GetString("RefreshAllCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh current card 的本地化字符串。
        /// </summary>
        public static string RefreshCurrentCard {
            get {
                return ResourceManager.GetString("RefreshCurrentCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh logging count 的本地化字符串。
        /// </summary>
        public static string RefreshLoggingCount {
            get {
                return ResourceManager.GetString("RefreshLoggingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Folder 的本地化字符串。
        /// </summary>
        public static string RemoveFolder {
            get {
                return ResourceManager.GetString("RemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution (Position): 的本地化字符串。
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select picture as wallpaper 的本地化字符串。
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set as specified image 的本地化字符串。
        /// </summary>
        public static string SetSpecifiedImage {
            get {
                return ResourceManager.GetString("SetSpecifiedImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set wallpaper to the folder images 的本地化字符串。
        /// </summary>
        public static string SetWallpaperByFolder {
            get {
                return ResourceManager.GetString("SetWallpaperByFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open main window 的本地化字符串。
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show main window when the program starts 的本地化字符串。
        /// </summary>
        public static string ShowWindowAtStartup {
            get {
                return ResourceManager.GetString("ShowWindowAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source code (GPL-3.0 license) 的本地化字符串。
        /// </summary>
        public static string SourceCode {
            get {
                return ResourceManager.GetString("SourceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Span 的本地化字符串。
        /// </summary>
        public static string Span {
            get {
                return ResourceManager.GetString("Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stretch 的本地化字符串。
        /// </summary>
        public static string Stretch {
            get {
                return ResourceManager.GetString("Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support 的本地化字符串。
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a completely open source wallpaper switch auxiliary tool, can be implemented as multiple monitor screen set wallpaper images respectively, and support the function of timer switch. 的本地化字符串。
        /// </summary>
        public static string SupportDescription {
            get {
                return ResourceManager.GetString("SupportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch next wallpaper 的本地化字符串。
        /// </summary>
        public static string SwitchNextWallpaper {
            get {
                return ResourceManager.GetString("SwitchNextWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch wallpaper When the program starts 的本地化字符串。
        /// </summary>
        public static string SwitchWallpaperOnStartup {
            get {
                return ResourceManager.GetString("SwitchWallpaperOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch next wallpapers 的本地化字符串。
        /// </summary>
        public static string SwitchWallpaperSet {
            get {
                return ResourceManager.GetString("SwitchWallpaperSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow system 的本地化字符串。
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string TabAbout {
            get {
                return ResourceManager.GetString("TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monitor 的本地化字符串。
        /// </summary>
        public static string TabMonitor {
            get {
                return ResourceManager.GetString("TabMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text documents 的本地化字符串。
        /// </summary>
        public static string TextDocuments {
            get {
                return ResourceManager.GetString("TextDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks 的本地化字符串。
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The project relies on components provided by the following open source projects: 的本地化字符串。
        /// </summary>
        public static string ThanksDescription {
            get {
                return ResourceManager.GetString("ThanksDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile 的本地化字符串。
        /// </summary>
        public static string Tile {
            get {
                return ResourceManager.GetString("Tile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View current image 的本地化字符串。
        /// </summary>
        public static string ViewCurrentImage {
            get {
                return ResourceManager.GetString("ViewCurrentImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View last setting image 的本地化字符串。
        /// </summary>
        public static string ViewLastSettingImage {
            get {
                return ResourceManager.GetString("ViewLastSettingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View setting image 的本地化字符串。
        /// </summary>
        public static string ViewSettingImage {
            get {
                return ResourceManager.GetString("ViewSettingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallpaper options 的本地化字符串。
        /// </summary>
        public static string WallpaperOptions {
            get {
                return ResourceManager.GetString("WallpaperOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Position of Wallpaper: 的本地化字符串。
        /// </summary>
        public static string WallpaperPosition {
            get {
                return ResourceManager.GetString("WallpaperPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White 的本地化字符串。
        /// </summary>
        public static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yellow 的本地化字符串。
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
